
version: "3.7"
services:

  site_ui:
    container_name: site_ui
    build:
      context: ./
      dockerfile: Dockerfile.site-ui
    restart: always
    volumes:
      - ./apps/showcase-ui/nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - NODE_ENV=production

  certbot:
    user: root
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

  proxy:
    user: root
    container_name: proxy
    build: ./nginx
    restart: unless-stopped
    depends_on:
      - site_ui
    links:
      - site_ui
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/init-letsencrypt.sh:/etc/nginx/init-letsencrypt.sh
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
